CREATE TABLE `tracks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `artist` varchar(128) DEFAULT NULL,
  `title` varchar(128) DEFAULT NULL,
  `album` varchar(128) DEFAULT NULL,
  `genre` varchar(64) DEFAULT NULL,
  `source` varchar(32) DEFAULT NULL,
  `duration` time DEFAULT '00:00:00',
  `publisher` varchar(64) DEFAULT NULL,
  `composer` varchar(64) DEFAULT NULL,
  `track` varchar(16) DEFAULT NULL,
  `copyright` varchar(64) DEFAULT NULL,
  `disc` varchar(16) DEFAULT NULL,
  `parent` int(11) NOT NULL,
  `fname` varchar(128) NOT NULL,
  `namespace` varchar(16) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `artist` (`artist`),
  KEY `title` (`title`),
  KEY `parent` (`parent`)
) ENGINE=InnoDB AUTO_INCREMENT=10871 DEFAULT CHARSET=latin1;
